<?php
/** @var \Algolia\AlgoliaSearch\Block\TopSearch $block */
$placeholder = __('Search for products, categories, ...');
?>

<?php if ($block->isDefaultSelector()): ?>
    <div class="block block-search">
        <div class="block block-title"><strong><?php echo __("Search") ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php echo $block->getResultUrl() ?>" method="get">
                <div id="algolia-searchbox">
                    <div class="field search">
                        <label class="label" for="search" data-role="minisearch-label">
                            <span><?php echo __("Search") ?></span>
                        </label>
                        <div class="control">
                            <input id="search" type="text" name="<?php echo $block->getQueryParamName() ?>" value="" class="input-text algolia-search-input" maxlength="128" autocomplete="off" spellcheck="false" autocorrect="off" autocapitalize="off" placeholder="<?php echo $placeholder; ?>">
                            <img class="clear-query-autocomplete" src="<?php echo $block->getViewFileUrl('Algolia_AlgoliaSearch::cross.png'); ?>" />
                            <svg id="algolia-glass" xmlns="http://www.w3.org/2000/svg" class="magnifying-glass" width="24" height="24" viewBox="0 0 128 128" >
                                <g transform="scale(4)">
                                    <path stroke-width="3" d="M19.5 19.582l9.438 9.438"></path>
                                    <circle stroke-width="3" cx="12" cy="12" r="10.5" fill="none"></circle>
                                    <path d="M23.646 20.354l-3.293 3.293c-.195.195-.195.512 0 .707l7.293 7.293c.195.195.512.195.707 0l3.293-3.293c.195-.195.195-.512 0-.707l-7.293-7.293c-.195-.195-.512-.195-.707 0z" ></path>
                                </g>
                            </svg>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>