<!--
//================================
//
// Search box
//
//================================
-->

<?php

$group_id = $this->customerSession->getCustomer()->getGroupId();
$currency_code = $this->storeManager->getStore()->getCurrentCurrencyCode();
$price_key = $this->config->isCustomerGroupsEnabled($this->storeManager->getStore()->getStoreId()) ? '.'.$currency_code.'.group_'.$group_id : '.'.$currency_code.'.default';

$image_base_url = $this->storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$title = '';
$description = '';
$content = '';
$imgHtml = '';

if($this->config->isInstantEnabled() && $this->config->replaceCategories() && $this->request->getControllerName() == 'category')
{
    $category = $this->registry->registry('current_category');
    $title = $category->getName();

    if ($category && $category->getDisplayMode() !== 'PAGE')
    {
        $category->getUrlInstance()->setStore($this->storeManager->getStore()->getStoreId());

        if ($category->getDisplayMode() == 'PRODUCTS_AND_PAGE')
        {
            $page           = $category->getLandingPage();
            $block          = $this->objectManager->create('\Magento\Cms\Model\Block');
            $cms_block      = $block->load($page);

            $description    = $category->getDescription();
            $content        = $this->getLayout()->createBlock('cms/block')->setBlockId($page)->toHtml();

            if ($category->getImageUrl())
            {
                $imgHtml = '<p class="category-image"><img src="'.$category->getImageUrl().'" alt="'.$this->escapeHtml($category->getName()).'" title="'.$this->escapeHtml($category->getName()).'" /></p>';
                $imgHtml = $this->helper('catalog/output')->categoryAttribute($category, $imgHtml, 'image');
            }
        }
    }
}

$placeholder = __('Search for products, categories, ...');

?>

<?php if ($this->config->isDefaultSelector()): ?>

    <div class="block block-search">
        <div class="block block-title"><strong>Search</strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php echo $this->catalogSearchHelper->getResultUrl() ?>" method="get">
                <div id="algolia-searchbox">
                    <div class="field search">
                        <label class="label" for="search" data-role="minisearch-label">
                            <span>Search</span>
                        </label>
                        <div class="control">
                            <input id="search" type="text" name="<?php echo $this->catalogSearchHelper->getQueryParamName() ?>" value="" class="input-text algolia-search-input" maxlength="128" autocomplete="off" spellcheck="false" autocorrect="off" autocapitalize="off" placeholder="<?php echo $placeholder; ?>">
                            <img class="clear-query-autocomplete" src="<?php echo $block->getViewFileUrl('Algolia_AlgoliaSearch::cross.png'); ?>" />
                            <svg id="algolia-glass" xmlns="http://www.w3.org/2000/svg" class="magnifying-glass" width="24" height="24" viewBox="0 0 128 128" >
                                <g transform="scale(4)">
                                    <path stroke-width="3" d="M19.5 19.582l9.438 9.438"></path>
                                    <circle stroke-width="3" cx="12" cy="12" r="10.5" fill="none"></circle>
                                    <path d="M23.646 20.354l-3.293 3.293c-.195.195-.195.512 0 .707l7.293 7.293c.195.195.512.195.707 0l3.293-3.293c.195-.195.195-.512 0-.707l-7.293-7.293c-.195-.195-.512-.195-.707 0z" ></path>
                                </g>
                            </svg>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>

<!--
//================================
//
// Multi-category Autocomplete
//
//================================
-->

<!-- Product hit template -->
<script type="text/template" id="autocomplete_products_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        {{#thumbnail_url}}
        <div class="thumb"><img src="{{thumbnail_url}}" /></div>
        {{/thumbnail_url}}

        <div class="info">
            {{{_highlightResult.name.value}}}

            <div class="algoliasearch-autocomplete-category">
                {{#categories_without_path}}
                <?php echo __('in'); ?> {{{categories_without_path}}}
                {{/categories_without_path}}

                {{#_highlightResult.color}}
                {{#_highlightResult.color.value}}
                <span>
                   {{#categories_without_path}} | {{/categories_without_path}} Color:  {{{_highlightResult.color.value}}}
                </span>
                {{/_highlightResult.color.value}}
                {{/_highlightResult.color}}
            </div>

            <div class="algoliasearch-autocomplete-price">
                    <span class="after_special {{#price<?php echo $price_key; ?>_original_formated}}promotion{{/price<?php echo $price_key; ?>_original_formated}}">
                        {{price<?php echo $price_key; ?>_formated}}
                    </span>

                {{#price<?php echo $price_key; ?>_original_formated}}
                    <span class="before_special">
                        {{price<?php echo $price_key; ?>_original_formated}}
                    </span>
                {{/price<?php echo $price_key; ?>_original_formated}}
            </div>
        </div>
    </a>
</script>

<!-- Category hit template -->
<script type="text/template" id="autocomplete_categories_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        {{#image_url}}
        <div class="thumb">
            <img src="{{image_url}}" />
        </div>
        {{/image_url}}

        {{#image_url}}
        <div class="info">
            {{/image_url}}
            {{^image_url}}
            <div class="info-without-thumb">
                {{#_highlightResult.path}}
                {{{_highlightResult.path.value}}}
                {{/_highlightResult.path}}
                {{^_highlightResult.path}}
                {{{path}}}
                {{/_highlightResult.path}}

                {{#product_count}}
                <small>({{product_count}})</small>
                {{/product_count}}

            </div>
            <div class="clearfix"></div>
            {{/image_url}}
        </div>
    </a>
</script>

<!-- Page hit template -->
<script type="text/template" id="autocomplete_pages_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        <div class="info-without-thumb">
            {{{_highlightResult.name.value}}}
            {{#content}}
            <div class="details">
                {{{content}}}
            </div>
            {{/content}}
        </div>
        <div class="clearfix"></div>
    </a>
</script>

<!-- Extra attribute hit template -->
<script type="text/template" id="autocomplete_extra_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        <div class="info-without-thumb">
            {{{_highlightResult.value.value}}}
        </div>
        <div class="clearfix"></div>
    </a>
</script>

<!-- Suggestion hit template -->
<script type="text/template" id="autocomplete_suggestions_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        <svg xmlns="http://www.w3.org/2000/svg" class="algolia-glass-suggestion magnifying-glass" width="24" height="24" viewBox="0 0 128 128" >
            <g transform="scale(2.5)">
                <path stroke-width="3" d="M19.5 19.582l9.438 9.438"></path>
                <circle stroke-width="3" cx="12" cy="12" r="10.5" fill="none"></circle>
                <path d="M23.646 20.354l-3.293 3.293c-.195.195-.195.512 0 .707l7.293 7.293c.195.195.512.195.707 0l3.293-3.293c.195-.195.195-.512 0-.707l-7.293-7.293c-.195-.195-.512-.195-.707 0z" ></path>
            </g>
        </svg>
        <div class="info-without-thumb">
            {{{_highlightResult.query.value}}}

            {{#category}}
            <span class="text-muted"><?php echo __('in'); ?></span> <span class="category-tag">{{category}}</span>
            {{/category}}
        </div>
        <div class="clearfix"></div>
    </a>
</script>


<!--
//================================
//
// Instant search results page
//
//================================
-->



<!-- Wrapping template -->
<script type="text/template" id="instant_wrapper_template">
    {{#findAutocomplete}}
    <div id="algolia-autocomplete-container"></div>
    {{/findAutocomplete}}
    <div id="algolia_instant_selector" class="<?php echo count($this->config->getFacets()) > 0 ? ' with-facets' : '' ?>">

        <?php if ($title || $imgHtml || $description || $content): ?>
            <div class="row">
                <div class="col-md-12">
                    <div id="algolia-static-content">
                        <div class="page-title category-title">
                            <h1><?php echo $title; ?></h1>
                        </div>
                        <div>
                            <?php echo $imgHtml; ?>
                        </div>
                        <div class="category-description std">
                            <?php echo $description; ?>
                        </div>
                        <?php echo $content; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-md-3" id="algolia-left-container">
                <div id="refine-toggle" class="visible-xs visible-sm">+ <?php echo __('Refine'); ?></div>
                <div class="hidden-xs hidden-sm" id="instant-search-facets-container">
                    <div id="current-refinements"></div>
                </div>
            </div>

            <div class="col-md-9" id="algolia-right-container">
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            {{#second_bar}}
                            <div id="instant-search-bar-container">
                                <div id="instant-search-box">
                                    <div class="instant-search-bar-label">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="magnifying-glass" width="24" height="24" viewBox="0 0 128 128">
                                            <g transform="scale(4)">
                                                <path stroke-width="3" d="M19.5 19.582l9.438 9.438"></path>
                                                <circle stroke-width="3" cx="12" cy="12" r="10.5" fill="none"></circle>
                                                <path d="M23.646 20.354l-3.293 3.293c-.195.195-.195.512 0 .707l7.293 7.293c.195.195.512.195.707 0l3.293-3.293c.195-.195.195-.512 0-.707l-7.293-7.293c-.195-.195-.512-.195-.707 0z"></path>
                                            </g>
                                        </svg>
                                        <span>Current search</span>
                                    </div>
                                    <div class="instant-search-bar-wrapper">
                                        <label for="instant-search-bar">
                                            <?php echo __('Search :'); ?>
                                        </label>

                                        <input placeholder="<?php echo __('Search for products'); ?>" id="instant-search-bar" type="text" autocomplete="off" spellcheck="false" autocorrect="off" autocapitalize="off" />

                                        <img class="clear-query-instant" src="<?php echo $block->getViewFileUrl('Algolia_AlgoliaSearch::cross.png'); ?>" />
                                    </div>
                                </div>
                            </div>
                            {{/second_bar}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div>
                        <div class="hits">
                            <div class="infos">
                                <div class="pull-left" id="algolia-stats"></div>
                                <div class="pull-right">
                                    <div class="sort-by-label pull-left">
                                        <?php echo __('SORT BY'); ?>
                                    </div>
                                    <div class="pull-left" id="algolia-sorts"></div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div id="instant-search-results-container"></div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="text-center">
                    <div id="instant-search-pagination-container"></div>
                </div>
            </div>
        </div>

    </div>
</script>

<script type="text/template" id="instant-hit-template">
    <div class="col-md-4 col-sm-6">
        <div class="result-wrapper">
            <a href="{{url}}" class="result">
                <div class="result-content">
                    <div class="result-thumbnail">
                        {{#image_url}}<img src="{{{ image_url }}}" />{{/image_url}}
                        {{^image_url}}<span class="no-image"></span>{{/image_url}}
                    </div>
                    <div class="result-sub-content">
                        <h3 class="result-title text-ellipsis">
                            {{{ _highlightResult.name.value }}}
                        </h3>
                        <div class="ratings">
                            <div class="result-sub-content">
                                <div class="ratings">
                                    <div class="rating-box">
                                        <div class="rating" style="width:{{rating_summary}}%" width="148" height="148"></div>
                                    </div>
                                </div>
                                <div class="price">
                                    <div class="price-wrapper">
                                        <div>
                                            <span class="after_special {{#price<?php echo $price_key; ?>_original_formated}}promotion{{/price<?php echo $price_key; ?>_original_formated}}">
                                                {{price<?php echo $price_key; ?>_formated}}
                                            </span>

                                            {{#price<?php echo $price_key; ?>_original_formated}}
                                                <span class="before_special">
                                                    {{price<?php echo $price_key; ?>_original_formated}}
                                                </span>
                                            {{/price<?php echo $price_key; ?>_original_formated}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="result-description text-ellipsis">{{{ _highlightResult.description.value }}}</div>

                        {{#isAddToCartEnabled}}
                        {{#in_stock}}
                        <form action="<?php echo $this->storeManager->getStore()->getBaseUrl(); ?>/checkout/cart/add/product/{{objectID}}" method="post">
                            <input type="hidden" name="form_key" value="<?php echo $this->form->getFormKey(); ?>" />
                            <input type="hidden" name="qty" value="1">
                            <button type="submit"><?php echo __('Add to Cart'); ?></button>
                        </form>
                        {{/in_stock}}
                        {{/isAddToCartEnabled}}
                    </div>
                </div>
                <div class="clearfix"></div>
            </a>
        </div>
    </div>
</script>

<script type="text/template" id="instant-stats-template">
    {{#hasOneResult}}<strong>1</strong> <?php echo __('result'); ?> found{{/hasOneResult}}
    {{#hasManyResults}}{{^hasNoResults}}{{first}}-{{last}} out of{{/hasNoResults}} <strong>{{#helpers.formatNumber}}{{nbHits}}{{/helpers.formatNumber}} <?php echo __('results found'); ?></strong>{{/hasManyResults}}
    <?php echo __('in'); ?> {{seconds}} <?php echo __('seconds'); ?>
</script>

<script type="text/template" id="facet-template">
    <div class="sub_facet {{#isRefined}}checked{{/isRefined}}">
        <input class="facet_value" {{#isRefined}}checked{{/isRefined}} type="checkbox">
        {{name}}
        <span class="count">{{count}}</span>
    </div>
</script>


<script type="text/template" id="current-refinements-template">
    <div class="cross-wrapper">
        <img src="<?php echo $block->getViewFileUrl("Algolia_AlgoliaSearch::cross.png"); ?>" />
    </div>
    <div class="current-refinement-wrapper">
        {{#label}}
        <span class="current-refinement-label">{{label}}{{^operator}}:{{/operator}}</span>
        {{/label}}
        {{#operator}}
        {{{displayOperator}}}
        {{/operator}}
        {{#exclude}}-{{/exclude}}
        <span class="current-refinement-name">{{name}}</span>
    </div>
</script>

<script type="text/template" id="menu-template">
    <div class="autocomplete-wrapper">
        <div class="col9">
            <div class="aa-dataset-products"></div>
        </div>
        <div class="col3">
            <div class="other-sections">
                <div class="aa-dataset-suggestions"></div>
                <?php for ($i = 0; $i < 10; $i++): ?>
                    <div class="aa-dataset-<?php echo $i; ?>"></div>
                <?php endfor; ?>
            </div>
        </div>
    </div>
</script>

<!--
//================================
//
// JavaScript
//
//================================
-->


<script type="text/javascript">
    //<![CDATA[

    requirejs(['algoliaBundle'], function(algoliaBundle) {
        algoliaBundle.$(function ($) {
            algoliaConfig.autocomplete.templates = {
                suggestions: algoliaBundle.Hogan.compile($('#autocomplete_suggestions_template').html()),
                products: algoliaBundle.Hogan.compile($('#autocomplete_products_template').html()),
                categories: algoliaBundle.Hogan.compile($('#autocomplete_categories_template').html()),
                pages: algoliaBundle.Hogan.compile($('#autocomplete_pages_template').html()),
                additionnalSection: algoliaBundle.Hogan.compile($('#autocomplete_extra_template').html())
            };

            var algolia_client = algoliaBundle.algoliasearch(algoliaConfig.applicationId, algoliaConfig.apiKey);

            if (algoliaConfig.instant.enabled && (algoliaConfig.isSearchPage || !algoliaConfig.autocomplete.enabled))
            {
                if ($(algoliaConfig.instant.selector).length <= 0)
                    throw '[Algolia] Invalid instant-search selector: ' + algoliaConfig.instant.selector;

                if (algoliaConfig.autocomplete.enabled && $(algoliaConfig.instant.selector).find(algoliaConfig.autocomplete.selector).length > 0)
                    throw '[Algolia] You can\'t have a search input matching "' + algoliaConfig.autocomplete.selector +
                    '" inside you instant selector "' + algoliaConfig.instant.selector + '"';

                var instant_selector = !algoliaConfig.autocomplete.enabled ? ".algolia-search-input" : "#instant-search-bar";

                var wrapperTemplate = algoliaBundle.Hogan.compile($('#instant_wrapper_template').html());

                var findAutocomplete = algoliaConfig.autocomplete.enabled && $(algoliaConfig.instant.selector).find('#algolia-autocomplete-container').length > 0;

                if (findAutocomplete) {
                    $(algoliaConfig.instant.selector).find('#algolia-autocomplete-container').remove();
                }

                var div = document.createElement('div');
                $(div).addClass('algolia-instant-results-wrapper');
                $(algoliaConfig.instant.selector).addClass('algolia-instant-replaced-content');
                $(algoliaConfig.instant.selector).wrap(div);
                $('.algolia-instant-results-wrapper').append('<div class="algolia-instant-selector-results"></div>');

                $('.algolia-instant-selector-results').html(wrapperTemplate.render({second_bar: algoliaConfig.autocomplete.enabled, findAutocomplete: findAutocomplete})).show();

                /** Initialise instant search **/
                var search = algoliaBundle.instantsearch({
                    appId: algoliaConfig.applicationId,
                    apiKey: algoliaConfig.apiKey,
                    indexName: algoliaConfig.indexName + '_products',
                    urlSync: {
                        useHash: true,
                        trackedParameters: ['query', 'page', 'attribute:*', 'index']
                    }
                });

                search.addWidget({
                    getConfiguration: function () {
                        if (algoliaConfig.request.query.length > 0 && location.hash.length < 1) {
                            return { query: algoliaConfig.request.query }
                        }
                        return {};
                    },
                    init: function(data) {
                        if (algoliaConfig.request.refinement_key.length > 0) {
                            data.helper.toggleRefine(algoliaConfig.request.refinement_key, algoliaConfig.request.refinement_value);
                        }

                        if (algoliaConfig.isCategoryPage) {
                            data.helper.addNumericRefinement('visibility_catalog', '=', 1);
                        }
                        else {
                            data.helper.addNumericRefinement('visibility_search', '=', 1);
                        }
                    },
                    render: function (data) {
                        if (! algoliaConfig.isSearchPage) {
                            if (data.results.query.length === 0) {
                                $('.algolia-instant-replaced-content').show();
                                $('.algolia-instant-selector-results').hide();
                            }
                            else {
                                $('.algolia-instant-replaced-content').hide();
                                $('.algolia-instant-selector-results').show();
                            }
                        }
                    }
                });

                /** Search bar **/
                search.addWidget(
                    algoliaBundle.instantsearch.widgets.searchBox({
                        container: instant_selector,
                        placeholder: 'Search for products'
                    })
                );

                /** Stats **/
                search.addWidget(
                    algoliaBundle.instantsearch.widgets.stats({
                        container: '#algolia-stats',
                        templates: {
                            body: $('#instant-stats-template').html()
                        },
                        transformData: function (data) {
                            data.first = data.page * data.hitsPerPage + 1;
                            data.last = Math.min(data.page * data.hitsPerPage + data.hitsPerPage, data.nbHits);
                            data.seconds = data.processingTimeMS / 1000;

                            return data;
                        }
                    })
                );

                /** Sorts **/
                algoliaConfig.sortingIndices.unshift({
                    name: algoliaConfig.indexName + '_products',
                    label: '<?php echo __('Relevance'); ?>'
                });

                search.addWidget(
                    algoliaBundle.instantsearch.widgets.sortBySelector({
                        container: '#algolia-sorts',
                        indices: algoliaConfig.sortingIndices,
                        cssClass: 'form-control'
                    })
                );

                /** Hits **/
                search.addWidget(
                    algoliaBundle.instantsearch.widgets.hits({
                        container: '#instant-search-results-container',
                        templates: {
                            item: $('#instant-hit-template').html()
                        },
                        transformData: {
                            item: function (hit) {
                                hit = transformHit(hit, algoliaConfig.priceKey);
                                hit.isAddToCartEnabled = algoliaConfig.instant.isAddToCartEnabled;

                                return hit;
                            }
                        },
                        hitsPerPage: algoliaConfig.hitsPerPage
                    })
                );

                search.addWidget({
                    suggestions: [],
                    init: function () {
                        if (algoliaConfig.showSuggestionsOnNoResultsPage) {
                            var $this = this;
                            $.each(algoliaConfig.popularQueries.slice(0, Math.min(4, algoliaConfig.popularQueries.length)), function (i, query) {
                                query = $('<div>').html(query).text(); //xss
                                $this.suggestions.push('<a href="' + algoliaConfig.baseUrl + '/catalogsearch/result/?q=' + encodeURIComponent(query) + '">' + query + '</a>');
                            });
                        }
                    },
                    render: function (data) {
                        if (data.results.hits.length === 0) {
                            var content = '<div class="no-results">';
                            content += '<div><b><?php echo __('No products for query'); ?> "' + $("<div>").text(data.results.query).html() + '</b>"</div>';
                            content += '<div class="popular-searches">';

                            if (algoliaConfig.showSuggestionsOnNoResultsPage && this.suggestions.length > 0) {
                                content += '<div><?php echo __('You can can try one of the popular search queries'); ?></div>' + this.suggestions.join(', ');
                            }

                            content += '</div>';
                            content += '<?php echo __('or'); ?> <a href="' + algoliaConfig.baseUrl + '/catalogsearch/result/?q=__empty__"><?php echo __('See all products'); ?></a>'

                            content += '</div>';

                            $('#instant-search-results-container').html(content);
                        }
                    }
                });

                /** Facets **/
                var wrapper = document.getElementById('instant-search-facets-container');

                var attributes = [];

                $.each(algoliaConfig.facets, function (i, facet) {
                    var name = facet.attribute;

                    if (name === 'categories') {
                        if (algoliaConfig.isCategoryPage) {
                            return;
                        }
                        name = 'categories.level0';
                    }

                    if (name === 'price') {
                        name = facet.attribute + algoliaConfig.priceKey
                    }

                    attributes.push({
                        name: name,
                        label: facet.label ? facet.label : facet.attribute
                    });
                });

                search.addWidget(
                    algoliaBundle.instantsearch.widgets.currentRefinedValues({
                        container: '#current-refinements',
                        cssClasses: {
                            root: 'facet'
                        },
                        templates: {
                            header: '<div class="name">' + '<?php echo __('Selected Filters'); ?>' + '</div>',
                            item: $('#current-refinements-template').html()
                        },
                        attributes: attributes,
                        onlyListedAttributes: true
                    })
                );

                var customAttributeFacet = {
                    categories: function(facet, templates) {
                        var hierarchical_levels = [];
                        for (var l = 0; l < 10; l++)
                            hierarchical_levels.push('categories.level' + l.toString());

                        var hierarchicalMenuParams = {
                            container: facet.wrapper.appendChild(document.createElement('div')),
                            attributes: hierarchical_levels,
                            separator: ' /// ',
                            alwaysGetRootLevel: true,
                            templates: templates,
                            sortBy: ['name:asc'],
                            cssClasses: {
                                list: 'hierarchical',
                                root: 'facet hierarchical'
                            }
                        };

                        hierarchicalMenuParams.templates.item = '' +
                            '<div class="ais-hierearchical-link-wrapper">' +
                            '<a class="{{cssClasses.link}}" href="{{url}}">{{name}}' +
                            '{{#isRefined}}<img class="cross-circle" src="<?php echo $block->getViewFileUrl('Algolia_AlgoliaSearch::cross-circle.png'); ?>"/>{{/isRefined}}' +
                            '<span class="{{cssClasses.count}}">{{#helpers.formatNumber}}{{count}}{{/helpers.formatNumber}}</span></a>' +
                            '</div>';

                        if (algoliaConfig.request.path.length > 0) {
                            hierarchicalMenuParams.rootPath = algoliaConfig.request.path;
                        }

                        return algoliaBundle.instantsearch.widgets.hierarchicalMenu(hierarchicalMenuParams);
                    }
                };

                $.each(algoliaConfig.facets, function (i, facet) {

                    if (facet.attribute.indexOf("price") !== -1)
                        facet.attribute = facet.attribute + algoliaConfig.priceKey;

                    facet.wrapper = wrapper;

                    var templates = {
                        header: '<div class="name">' + (facet.label ? facet.label : facet.attribute) + '</div>'
                    };

                    var widget = customAttributeFacet[facet.attribute] !== undefined ?
                        customAttributeFacet[facet.attribute](facet, templates) :
                        getFacetWidget(facet, templates);

                    search.addWidget(widget);
                });

                /** Pagination **/
                search.addWidget(
                    algoliaBundle.instantsearch.widgets.pagination({
                        container: '#instant-search-pagination-container',
                        cssClass: 'algolia-pagination',
                        showFirstLast: false,
                        maxPages: 1000,
                        labels: {
                            previous: '<?php echo __('Previous page'); ?>',
                            next: '<?php echo __('Next page'); ?>'
                        },
                        scrollTo: 'body'
                    })
                );

                function startInstantSearch() {
                    search.start();

                    handleInputCrossInstant($(instant_selector));

                    var instant_search_bar = $(instant_selector);
                    if (instant_search_bar.is(":focus") === false) {
                        focusInstantSearchBar(search, instant_search_bar);
                    }

                    if (algoliaConfig.autocomplete.enabled) {
                        $('#search_mini_form').addClass('search-page');
                    }

                    $(document).on('click', '.ais-hierarchical-menu--link, .ais-refinement-list--checkbox', function () {
                        focusInstantSearchBar(search, instant_search_bar);
                    });
                }

                if (algoliaConfig.isSearchPage) {
                    startInstantSearch();
                }
                else {
                    (function () {
                        var isStarted = false;

                        $(instant_selector).one('focus', (function () {
                            if (!isStarted) {
                                startInstantSearch();
                            }
                            isStarted = true;
                        }));
                    })();
                }
            }

            /*****************
             **
             ** AUTOCOMPLETION MENU
             **
             *****************/

            /** keep it after instant search to be able to bind to the recreated <div id="algolia-autocomplete-container"></div> **/
            if (algoliaConfig.autocomplete.enabled) {
                var sources = [];

                /** Add products and categories that are required sections **/
                var nb_cat = algoliaConfig.autocomplete.nbOfCategoriesSuggestions >= 1 ? algoliaConfig.autocomplete.nbOfCategoriesSuggestions: 2;
                var nb_pro = algoliaConfig.autocomplete.nbOfProductsSuggestions >= 1 ? algoliaConfig.autocomplete.nbOfProductsSuggestions : 6;
                var nb_que = algoliaConfig.autocomplete.nbOfQueriesSuggestions >= 0 ? algoliaConfig.autocomplete.nbOfQueriesSuggestions : 0;

                if (nb_que > 0) {
                    algoliaConfig.autocomplete.sections.unshift({ hitsPerPage: nb_que, label: '', name: "suggestions"});
                }

                algoliaConfig.autocomplete.sections.unshift({ hitsPerPage: nb_cat, label: <?php echo json_encode(__('Categories')); ?>, name: "categories"});
                algoliaConfig.autocomplete.sections.unshift({ hitsPerPage: nb_pro, label: <?php echo json_encode(__('Products')); ?>, name: "products"});

                var i = 0;
                $.each(algoliaConfig.autocomplete.sections, function (name, section) {
                    var source = getAutocompleteSource(section, algolia_client, $, i);

                    if (source)
                        sources.push(source);

                    /* Those sections have already specific placeholder, so do not use the default aa-dataset-{i} class */
                    if (section.name !== 'suggestions' && section.name !== 'products')
                        i++;

                });

                // setup the auto-completed search input
                $(algoliaConfig.autocomplete.selector).each(function (i) {
                    var menu = $(this);
                    var options = {
                        hint: false,
                        templates: {
                            dropdownMenu: '#menu-template'
                        },
                        dropdownMenuContainer: "#algolia-autocomplete-container",
                        debug: true
                    };

                    if (algoliaConfig.removeBranding === false) {
                        options.templates.footer = '<div class="footer_algolia"><span>Search by</span> <a href="https://www.algolia.com/?utm_source=magento&utm_medium=link&utm_campaign=magento_autocompletion_menu" target="_blank"><img src="<?php echo $block->getViewFileUrl('Algolia_AlgoliaSearch::algolia-logo.png'); ?>" /></a></div>';
                    }

                    $(this)
                        .autocomplete(options, sources)
                        .parent()
                        .attr('id', 'algolia-autocomplete-tt')
                        .on('autocomplete:updated', function (e) {
                            fixAutocompleteCssSticky(menu);
                        })
                        .on('autocomplete:updated', function (e) {
                            fixAutocompleteCssHeight(menu);
                        });

                    $(window).resize(function () {
                        fixAutocompleteCssSticky(menu);
                    });
                });
            }
        });
    });

    //]]>
</script>