<?php

/** @var \Magento\Backend\Block\Template $block */

/** @var \Algolia\AlgoliaSearch\ViewModel\Adminhtml\Support\Contact $view */
$view = $block->getViewModel();

?>

<h3><?php echo $block->escapeHtml(__('Contact Algolia')) ?></h3>

<?php if ($view->isExtensionSupportEnabled()) : ?>
    <form method="post" action="<?php echo $block->getUrl('*/*/contact') ?>" class="algolia_contact_form" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />

        <div class="row">
            <fieldset class="admin__fieldset col-l-7">
                <div class="admin__field _required">
                    <label for="name" class="admin__field-label">
                        <span><?php echo $block->escapeHtml(__('Your name')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <input
                            type="text"
                            name="name"
                            id="name"
                            value="<?php echo $view->getDefaultName(); ?>"
                            class="admin__control-text"
                            data-validate="{required: true}" />
                    </div>
                </div>

                <div class="admin__field _required">
                    <label for="email" class="admin__field-label">
                        <span><?php echo $block->escapeHtml(__('E-mail')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input
                            type="text"
                            name="email"
                            id="email"
                            value="<?php echo $view->getDefaultEmail(); ?>"
                            class="admin__control-text"
                            data-validate="{required: true, 'validate-email': true}" />
                    </div>
                </div>

                <div class="admin__field _required">
                    <label for="subject" class="admin__field-label">
                        <span><?php echo $block->escapeHtml(__('Subject')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input
                            type="text"
                            name="subject"
                            id="subject"
                            value="<?php echo $block->getRequest()->getParam('subject'); ?>"
                            class="admin__control-text"
                            data-validate="{required: true}" />
                    </div>
                </div>

                <div class="admin__field _required">
                    <label for="message" class="admin__field-label">
                        <span><?php echo $block->escapeHtml(__('Your message')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <textarea
                            name="message"
                            id="message"
                            class="admin__control-textarea"
                            placeholder="Please provide us context of your problem or question: what you were trying to achieve, what went wrong, etc."
                            data-validate="{required: true}"><?php echo $block->getRequest()->getParam('message'); ?></textarea>

                        <div class="admin__field-note">
                            <div class="note_icon">i</div>
                            <span>
                                To provide a better support, this information will be attached to your request:
                                <ul>
                                    <li>Magento and Algolia extension version numbers</li>
                                    <li>Algolia extension configuration</li>
                                    <li>
                                        Indexing queue information
                                        <?php echo $view->getTooltipHtml(__('
                                                - Number of jobs in indexing queue<br>
                                                - Information about last 20 failed indexing jobs<br>
                                                - Creation time of the oldest job in indexing queue
                                            '));
                                        ?>
                                    </li>
                                </ul>
                                <b>No personal information will be sent to Algolia.</b>
                            </span>
                        </div>
                        <br>
                        <div class="admin__actions-switch" data-role="switcher">
                            <input
                                type="checkbox"
                                class="admin__actions-switch-checkbox"
                                id="send_additional_info"
                                name="send_additional_info"
                                value="1"
                                checked />
                            <label class="admin__actions-switch-label" for="send_additional_info">
                                <span class="admin__actions-switch-text">
                                    Attach list of installed 3rd party modules and catalog size
                                    <?php echo $view->getTooltipHtml(__('
                                            The additional data can speed up the support process 
                                            by providing Algolia team more context on your implementation.
                                        '));
                                    ?>
                                </span>
                            </label>
                        </div>

                        <div class="button">
                            <button
                                type="submit"
                                name="sent"
                                value="sent"
                                class="action submit primary algolia-daterange-submit">
                               <?php echo $block->escapeHtml(__('Send')) ?>
                            </button>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="col-l-1"></div>
            <div class="col-l-3">
                <div class="heading">
                    <?php echo $block->escapeHtml(__('Related to your subject ...')) ?>
                </div>
                <div class="contact_results links"></div>
            </div>
        </div>
    </form>

<?php else: ?>

    <?php
        $helpIllustration = $block->getViewFileUrl('Algolia_AlgoliaSearch::images/illu-help.svg');
        $bookIllustration = $block->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-book.svg');
        $starsIllustration = $block->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-stars.svg');
    ?>
    <div class="access-denied-page algolia-denied-page">
        <span><img src="<?php echo $block->escapeUrl($helpIllustration) ?>" /></span>
        <div class="algolia-suggestions-header">
            <img src="<?php echo $block->escapeUrl($bookIllustration) ?>" class="book" />
            <p>There's <a href="https://www.algolia.com/doc/integration/magento-2/getting-started/quick-start/?utm_source=magento&utm_medium=extension&utm_campaign=magento_2&utm_term=shop-owner&utm_content=doc-link" target="_blank">Documentation, Tutorials and Videos</a> - But we also offer expert advice and solutions through direct email support by Algolia engineers and product specialists.</p>
        </div>
        <div class="algolia-suggestions-header algolia-suggestions-header-wbg">
            <img src="<?php echo $block->escapeUrl($starsIllustration) ?>" class="stars" />
            <p>To get access to this Algolia feature, please consider <a href="https://www.algolia.com/pricing" target="_blank" >upgrading to a higher plan</a>.</p>
        </div>
    </div>

<?php endif; ?>
