<?php

/** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\BaseAdminTemplate */

/** @var Algolia\AlgoliaSearch\ViewModel\Adminhtml\Analytics\Form $form */
$form = $this->getViewModel();

?>

<?php $isFormDisabled = !$form->isAnalyticsApiEnabled() ? ' disabled' : '' ?>
<div class="algolia-analytics-form" id="algolia-analytics-daterange">
    <form id="algolia-analytics-form" data-mage-init='{"validation":{}}' action="<?php echo $form->getFormAction() ?>"  method="post">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
        <div class="inline-field">
            <select name="type" class="select admin__control-select"<?php echo $isFormDisabled ?>>
                <?php foreach ($form->getSections() as $key => $section): ?>
                    <option value="<?php echo $key ?>"<?php echo $key == $form->getFormValue('type') ? ' selected' : '' ?>>
                        <?php echo ucwords($key) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="inline-field">
            <input type="text" id="analytics_from" name="from" <?php echo $isFormDisabled ?>
                   class="admin__control-text input-text date-range-analytics-from"
                   placeholder="<?php echo __('Start Date') ?>" value="<?php echo $form->getFormValue('from') ?>"/>
        </div>
        <span class="divide">-</span>
        <div class="inline-field">
            <input type="text" id="analytics_to" name="to" <?php echo $isFormDisabled ?>
                   class="admin__control-text input-text validate-date-range date-range-analytics-to"
                   placeholder="<?php echo __('End Date') ?>" value="<?php echo $form->getFormValue('to') ?>"/>
        </div>
        <button type="submit" class="action submit primary algolia-daterange-submit"<?php echo $isFormDisabled ?>>
            <?php echo __('Update') ?>
        </button>
    </form>
</div>

<script type="text/javascript">
    require(["jquery", "mage/calendar", "mage/backend/form", 'mage/tooltip'], function($) {
        $('#algolia-analytics-form').dateRange({
            dateFormat: "d MMM Y",
            from: {
                id: "analytics_from"
            },
            to: {
                id: "analytics_to"
            }
        });

        var analyticsForm = $('#algolia-analytics-form').form();
        analyticsForm.on('submit', function(e) {
            e.preventDefault();
            e.stopImmediatePropagation();

            if (analyticsForm.valid()) {
                $.ajax({
                    type: 'post',
                    url: analyticsForm.attr('action'),
                    data: analyticsForm.serialize(),
                    showLoader: true,
                    context: this,
                    dataType: 'json',
                    success: function (response) {
                        if (!response.error) {
                            $('#container').html(response.html_content);
                        } else {
                            alert('An error has occurred. Please try refreshing the page and submitting again.');
                        }
                    }
                });
            }
        });
    });
</script>