<?php if (!empty($block->getAnalytics())): ?>
    <div id="algolia-analyatics-diagram"></div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", {packages:['corechart']});
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {

            var data = new google.visualization.arrayToDataTable([
                ['Date', 'Searches', {type: 'string', role: 'tooltip', p: {'html': true}}, {role: 'style'}],
                <?php foreach ($block->getAnalytics() as $item): ?>
                ['<?php echo $item['formatted'] ?>', <?php echo $item['count'] ?>,
                    "<div style='padding: 1.5rem; line-height: 18px;'><strong style='font-size: 14px;'><?php echo $item['formatted'] ?></strong><br/><br/>" +
                    "<p>Searches: <strong style='color: #5468ff; padding-left: 3px;'><?php echo $item['count'] ?></strong></p>" +
                    "<p>Users: <strong style='color: #3a46a1; padding-left: 3px;'><?php echo $item['users'] ?></strong></p>" +
                    "<p>No Result Rate: <strong style='color: #3ab2bd; padding-left: 3px;'><?php echo round((int) $item['rate'] * 100, 2) . '%' ?></strong></p>" +
                    <?php if (isset($item['ctr'])): ?>
                        "<br/>" +
                        "<p>CTR: <strong style='color: #5468ff; padding-left: 3px;'><?php echo round((int) $item['ctr'] * 100, 2) . '%' ?></strong></p>" +
                        "<p>Conversion Rate: <strong style='color: #3a46a1; padding-left: 3px;'><?php echo round((int) $item['conversion'] * 100, 2) . '%' ?></strong></p>" +
                        "<p>Avg Click Position: <strong style='color: #3ab2bd; padding-left: 3px;'><?php echo $item['clickPos'] ? $item['clickPos'] : '-' ?></strong></p>" +
                    <?php endif ?>
                    "</div>",
                    'stroke-opacity: 0; fill-opacity: 0.75;'
                ],
                <?php endforeach ?>
            ]);

            var options = {
                chart: {
                    subtitle: 'Searches, Users, and No Result Rates',
                },
                colors: ['#5468ff', '#3a46a1', '#3ab2bd'],
                hAxis: {
                    baselineColor: 'grey',
                    textStyle: {
                        color: 'grey'
                    }
                },
                vAxis: {
                    baselineColor: 'grey',
                    minValue: 0,
                    textStyle: {
                        color: 'grey'
                    }
                },
                legend: {position: 'none'},
                tooltip: {isHtml: true},
                fontSize: 12,
                fontName: 'Open Sans'
            };

            var chart = new google.visualization.ColumnChart(document.getElementById('algolia-analyatics-diagram'));
            chart.draw(data, options);
        }
    </script>
<?php else: ?>
    <div class="dashboard-diagram-nodata">
        <span><?php echo __('No Data Found') ?></span>
    </div>
<?php endif ?>