<?php

/** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\BaseAdminTemplate */

/** @var \Algolia\AlgoliaSearch\ViewModel\Adminhtml\Landingpage\Suggestions $view */
$view = $this->getViewModel();

$emptyStateIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/illu-lpb.svg');
$bookIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-book.svg');
?>

<?php if ($view->getNbOfLandingPages() > 0) : ?>
    <div class="algolia-suggestions-header">
        <div class="close-box">x</div>
        <img src="<?php echo $bookIllustration ?>" class="book" />
        <p>The Landing Page Builder allows you to easily create customised landing pages out of search queries.</p>
        <p>It is a powerful marketing tool to promote products, with a strong focus on SEO. To find out more about the Landing Page Builder, please see our <a href="https://www.algolia.com/doc/integration/magento-2/merchandising/landing-page-builder/?utm_source=magento&utm_medium=extension&utm_campaign=magento_2&utm_term=shop-owner&utm_content=doc-link" target="_blank">documentation</a>.</p>
    </div>
<?php else: ?>
    <div class="algolia-no-lp">
        <span><img src="<?php echo $emptyStateIllustration ?>" /></span>
        <p class="bigtext">No landing page yet!</p>
        <div class="algolia-suggestions-header">
            <img src="<?php echo $bookIllustration ?>" class="book" />
            <p>The Landing Page Builder allows you to easily create customised landing pages out of search queries.</p>
            <p>It is a powerful marketing tool to promote products, with a strong focus on SEO. To find out more about the Landing Page Builder, please see our <a href="https://www.algolia.com/doc/integration/magento-2/merchandising/landing-page-builder/?utm_source=magento&utm_medium=extension&utm_campaign=magento_2&utm_term=shop-owner&utm_content=doc-link" target="_blank">documentation</a>.</p>
        </div>
        <p><a class="new-lp" href="<?php echo $this->getUrl('*/*/edit'); ?>" >Create a new landing page</a></p>
    </div>
<?php endif ?>