<?php

/** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\BaseAdminTemplate */

/** @var \Algolia\AlgoliaSearch\ViewModel\Adminhtml\Landingpage\Suggestions $view */
$view = $this->getViewModel();

$emptyStateIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/illu-lpb.svg');
$bookIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-book.svg');
?>

<div class="algolia-suggestions-header">
    <div class="close-box">x</div>
    <img src="<?php echo $bookIllustration ?>" class="book" />
    <p>The Landing Page Builder allows you to easily create customised landing pages out of search queries.</p>
    <p>It is a powerful marketing tool to promote products, with a strong focus on SEO.</p>
</div>

<?php if ($view->getNbOfLandingPages() === 0) : ?>
    <div class="algolia-no-lp">
        <span><img src="<?php echo $emptyStateIllustration ?>" /></span>
        <p class="bigtext">No landing page yet!</p>
        <p><a class="new-lp" href="<?php echo $this->getUrl('*/*/edit'); ?>" >Create a new landing page</a></p>
    </div>
<?php endif ?>