<?php
$bookIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-book.svg');
?>

<div class="algolia-suggestions-header">
    <img src="<?php echo $bookIllustration ?>" class="book" />
    <p>Landing pages are created with the aim to boost your marketing activities with strong focus on SEO. They are based on Algolia's Query Rules.</p>
    <p>Read more about the landing page builder in our <a href="#">Documentation</a>.</p>
</div>