<?php
/** @var \Magento\Backend\Block\Template $block */
?>
<div class="algolia-admin-content">
    <div class="algolia-admin-content-wrapper">
        <div class="algolia-admin-content-links">
            <p>
                <span>
                    <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-docs.svg')) ?>">
                    <a target="_blank" href="https://www.algolia.com/doc/integration/magento-2/how-it-works/indexing-queue/?utm_source=magento&amp;utm_medium=extension&amp;utm_campaign=magento_2&amp;utm_term=shop-owner&amp;utm_content=doc-link"><?php echo $block->escapeHtml(__('Indexing queue documentation')) ?></a>
                </span>
            </p>
            <p>
                <span>
                    <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-docs.svg')) ?>">
                    <a target="_blank" href="https://www.algolia.com/doc/integration/magento-2/troubleshooting/data-indexes-queues/?utm_source=magento&amp;utm_medium=extension&amp;utm_campaign=magento_2&amp;utm_term=shop-owner&amp;utm_content=doc-link"><?php echo $block->escapeHtml(__('Indexing troubleshooting guide')) ?></a>
                </span>
            </p>
        </div>
        <div class="algolia-admin-content-videos">
            <p>
                <span><?php echo $block->escapeHtml(__('Related video:')) ?></span>
                <a target="_blank" href="https://www.youtube.com/watch?v=0V1BSKlCm10"><img src="https://img.youtube.com/vi/0V1BSKlCm10/mqdefault.jpg"></a>
                <a target="_blank" href="https://www.youtube.com/watch?v=0V1BSKlCm10"><?php echo $block->escapeHtml(__('The indexing queue')) ?></a>
            </p>
        </div>
    </div>
</div>
<?php if ($block->isQueueActive()) : ?>
    <div class="message message-notice notice algolia-notice">
        <div data-ui-id="messages-message-notice">
            <?php echo __('Status of the queue : <strong>%1</strong>.', $block->getQueueRunnerStatus()); ?>
            <p><?php echo __('Last Update : <strong>%1</strong>.', $block->getLastQueueUpdate()); ?></p>
            <?php $notices = $block->getNotices() ?>
            <?php foreach ($notices as $notice) : ?>
                <p><?php echo $notice ?></p>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>