<?php
/**
 * @see \Magento\Backend\Block\Denied
 */
$emptyStateIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/illu-querymerchandiser.svg');
$bookIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-book.svg');
$starsIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-stars.svg');
?>
<hr class="access-denied-hr"/>
<div class="access-denied-page algolia-denied-page">
    <span><img src="<?php echo $emptyStateIllustration ?>" /></span>
    <div class="algolia-suggestions-header">
        <img src="<?php echo $bookIllustration ?>" class="book" />
        <p>Easily promote or demote products for a search. Based on Algolia's Query rules, the Query Merchandiser allows you to enchance the ranking behaviour for specific search queries.</p>
        <p>Merchandising a query will create a new query rule (which are part of your Algolia plan). To find out more about the Query Merchandiser, please see our <a href="https://www.algolia.com/doc/integration/magento-2/getting-started/quick-start/" target="_blank">Documentation</a>.</p>
    </div>
    <div class="algolia-suggestions-header algolia-suggestions-header-wbg">
        <img src="<?php echo $starsIllustration ?>" class="stars" />
        <p>To get access to this Algolia feature, please consider <a href="https://www.algolia.com/pricing" target="_blank" >upgrading to a higher plan</a>.</p>
    </div>
</div>
