<?php

/** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\BaseAdminTemplate */

/** @var \Algolia\AlgoliaSearch\ViewModel\Adminhtml\Query\Suggestions $view */
$view = $this->getViewModel();

$emptyStateIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/illu-lpb.svg');
$bookIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-book.svg');
?>

<?php if ($view->getNbOfQueries() > 0) : ?>
    <div class="algolia-suggestions-header">
        <div class="close-box">x</div>
        <img src="<?php echo $bookIllustration ?>" class="book" />
        <p>Easily promote or demote products for a search. Based on Algolia's Query rules, the Query Merchandiser allows you to enchance the ranking behaviour for specific search queries.</p>
        <p>Merchandising a query will create a new query rule (which are part of your Algolia plan). To find out more about the Query Merchandiser, please see our <a href="https://www.algolia.com/doc/integration/magento-2/getting-started/quick-start/" target="_blank">Documentation</a>.</p>
    </div>
<?php else: ?>
    <div class="algolia-no-lp">
        <span><img src="<?php echo $emptyStateIllustration ?>" /></span>
        <p class="bigtext">No merchandised query yet!</p>
        <div class="algolia-suggestions-header">
            <img src="<?php echo $bookIllustration ?>" class="book" />
            <p>Easily promote or demote products for a search. Based on Algolia's Query rules, the Query Merchandiser allows you to enchance the ranking behaviour for specific search queries.</p>
            <p>Merchandising a query will create a new query rule (which are part of your Algolia plan). To find out more about the Query Merchandiser, please see our <a href="https://www.algolia.com/doc/integration/magento-2/getting-started/quick-start/" target="_blank">Documentation</a>.</p>
        </div>
        <p><a class="new-lp" href="<?php echo $this->getUrl('*/*/edit'); ?>" >Merchandise a new query</a></p>
    </div>
<?php endif ?>