<?php

/** @var $this \Algolia\AlgoliaSearch\Block\Adminhtml\BaseAdminTemplate */

/** @var \Algolia\AlgoliaSearch\ViewModel\Adminhtml\Query\Suggestions $view */
$view = $this->getViewModel();

$emptyStateIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/illu-lpb.svg');
$bookIllustration = $this->getViewFileUrl('Algolia_AlgoliaSearch::images/icon-book.svg');
?>

<?php if ($view->getNbOfQueries() > 0) : ?>
    <div class="algolia-suggestions-header">
        <div class="close-box">x</div>
        <img src="<?php echo $bookIllustration ?>" class="book" />
        <p>The Query Merchandiser allows you to easily manage the behaviour of your product listings according to particular queries.</p>
        <p>With this tool, you can promote / demote products and add a banner on top of the search results.</p>
    </div>
<?php else: ?>
    <div class="algolia-no-lp">
        <span><img src="<?php echo $emptyStateIllustration ?>" /></span>
        <p class="bigtext">No merchandised query yet!</p>
        <div class="algolia-suggestions-header">
            <img src="<?php echo $bookIllustration ?>" class="book" />
            <p>The Query Merchandiser allows you to easily manage the behaviour of your product listings according to particular queries.</p>
            <p>With this tool, you can promote / demote products and add a banner on top of the search results.</p>
        </div>
        <p><a class="new-lp" href="<?php echo $this->getUrl('*/*/edit'); ?>" >Merchandise a new query</a></p>
    </div>
<?php endif ?>