<script>
document.addEventListener("DOMContentLoaded", function(event) {
    requirejs(['algoliaAdminBundle'], function(algoliaAdminBundle) {
        algoliaAdminBundle.$(function ($) {
            $('form[action*="algoliasearch"] .accordion .config .label').css('width', 'auto');
            $('form[action*="algoliasearch"] .accordion .config .value').css('width', 'auto');

            var fixHelper = function(e, ui) {
                ui.children().each(function() {
                    $(this).width($(this).width());
                });

                return ui;
            };

            setTimeout(function () {
            	$('form[action*="algoliasearch"] .admin__control-table tbody').sortable({
                    containment: "parent",
                    items: 'tr',
                    tolerance: 'pointer',
                    helper: fixHelper,
                    start: function (event, ui) {
                        $(ui.item).css('margin-left', '10px');
                    }
                });

                $('form[action*="algoliasearch"] .admin__control-table tbody tr td').css('cursor', 'move');
            }, 1000);
        });
    });
});
</script>
