<div id="algolia-autocomplete-container"></div>
<script>
    require(['algoliaBundle','algoliaAutocomplete'], function(algoliaBundle, algoliaAutocomplete) {
        algoliaBundle.$(function ($) {
            algoliaAutocomplete({
                'suggestionsTemplate': '#autocomplete_suggestions_template',
                'productsTemplate': '#autocomplete_products_template',
                'categoriesTemplate': '#autocomplete_categories_template',
                'pagesTemplate': '#autocomplete_pages_template',
                'additionalSectionTemplate': '#autocomplete_extra_template'
            }, algoliaConfig, algolia);
        });
    });
</script>