<?php
/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Algolia\AlgoliaSearch\Block\Configuration $block
 */
?>

<script>
    <?php if ($block->getConfigHelper()->isInstantEnabled() && $block->isSearchPage() === true): ?>
        // Hide the instant-search selector ASAP to remove flickering. Will be re-displayed later with JS.
        document.write('<style type="text/css"><?php /* @escapeNotVerified */ echo $block->getConfigHelper()->getInstantSelector(); ?> { display:none }</style>');
    <?php endif; ?>

    window.algoliaConfig = <?php echo json_encode($block->getConfiguration()); ?>;
</script>

<!--[if lte IE 9]>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        algoliaBundle.$(function () {
            window.algoliaConfig.autofocus = false;
        });
    });
</script>
<![endif]-->
