<?php /** @var \Algolia\AlgoliaSearch\Block\Configuration $block */ ?>

<script>
    <?php
    if ($block->getConfigHelper()->isInstantEnabled() && $block->isSearchPage() === true) :
        $css = '<style type="text/css">'.$block->getConfigHelper()->getInstantSelector().' {display:none}</style>';
    ?>

        // Hide the instant-search selector ASAP to remove flickering. Will be re-displayed later with JS.
        document.write(<?php /* @noEscape */ echo $css; ?>);
    <?php
    endif;
    ?>

    window.algoliaConfig = <?php /* @noEscape */ echo json_encode($block->getConfiguration()); ?>;
</script>

<!--[if lte IE 9]>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        algoliaBundle.$(function () {
            window.algoliaConfig.autofocus = false;
        });
    });
</script>
<![endif]-->
